ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'ecom'), namespace='ecom'))
]

urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'ecom'
urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name='update_item'),
    path('process_order/', views.processOrder, name='process_order'),
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('<int:pk>/', views.ProductDetail.as_view(), name='details'),
    path('account/', views.userPage, name='userpage'),

    path('api/orders/all/', views.get_all_orders, name='getAllOrders'),
    path('api/orders/', views.orderDetails, name='order_details_api'),
    path('api/orders/<int:pk>', views.orderDetails, name='order_details'),
    path('api/bonuses/<int:pk>', views.bonusesHistory, name='bonusesHistory'),
    path('api/customer/<int:pk>', views.customerInfo, name='customerInfo'),
    path('api/customer/update', views.update_info, name='updateCustomer'),
    path('api/getCurrentUser/', views.get_current_user, name='getCurrentUser'),
    path('api/customerPhone/<str:phone_number>', views.get_customer_by_phone_number, name="getCustomerByPhone"),
    path('api/postNewBonuses/', views.post_new_bonuses, name="postNewBonuses"),
    path('api/order/acceptPayment/', views.order_accept_payment, name="acceptPayment"),
    path('api/order/serveOrder/', views.order_serve, name="serveOrder"),
    path('api/orders/getByPhone/<str:phone_number>', views.get_customer_orders_by_phone_number, name="getCustomerOrdersByPhone"),

    path('management/', views.management, name='management')
    ]

shop/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.db.models import Sum
from .utils import phone_validator

class Cafe(models.Model):
    adress = models.CharField(max_length=200, null=True)
    name = models.CharField(max_length=200, null=True)
    photo = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.adress


class Customer(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True, related_name='customer')
    phone_number = models.CharField('Phone Number', validators=[phone_validator], max_length=25)
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)

    def total_bonuses(self):
        boni = self.bonuses_set.all()
        sum = boni.aggregate(Sum('number_of_bonuses'))
        return sum['number_of_bonuses__sum']

    def __str__(self):
        return self.phone_number


class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    image = models.ImageField(null=True, blank=True)
    description = models.TextField(default='Here be descriptions')

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except ValueError:
            url = '/images/placeholder.png'
        return url


class Order(models.Model):
    PAYMENT_METHODS = (
        (1, 'Cash'),
        (2, 'Online')
        )
    customer_id = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    served = models.BooleanField(default=False, null=True, blank=False)
    is_paid = models.BooleanField(default=False, null=True, blank=False)
    payment_method = models.CharField(max_length=1, choices=PAYMENT_METHODS, null=True)
    transaction_id = models.CharField(max_length=200, null=True)
    cafe_id = models.ForeignKey(Cafe, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order_id = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    @property
    def get_total(self):
        total = self.product_id.price * self.quantity
        return total

    def __str__(self):
        return self.product_id.name

class Bonuses(models.Model):
    number_of_bonuses = models.IntegerField(default=0, null=True, blank=True)
    customer_id = models.ForeignKey(Customer, on_delete=models.CASCADE)
    worker_id = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

shop/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Customer
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CreateCustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['first_name', 'last_name', 'phone_number']


class UserEmailForm(ModelForm):
    class Meta:
        model = User
        fields = ['email']

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import models
from django.http import JsonResponse
from .utils import cartData, guestOrder, add_bonuses_for_transaction, phone_formating, update_order_item_quantity, process_placed_order, register_new_user
from .serializers import OrderSerializer, CustomerBonusesSerializer, CustomerSerializer, UserIdSerializer, AllOrdersSerializer, CustomerOrdersSerializer
import json
import datetime
from . forms import CreateUserForm, CreateCustomerForm, UserEmailForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from rest_framework.response import Response
from rest_framework.decorators import api_view
from django.contrib.auth.models import User
from .decorators import unauthenticated_user, allowed_users, the_same_user
from rest_framework import status
import phonenumbers

def store(request):
    """This view renders the main page of the e-shop showing all the products in the database
    """
    data = cartData(request)

    cartItems = data['cartItems']

    products = models.Product.objects.all()
    ctx = {
        'products':products,
        'cartItems': cartItems
        }
    return render(request, 'ecom/store.html', ctx)

def cart(request):
    """This view renders the cart of the user
    """
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    ctx = {
        'items': items,
        'order': order,
        'cartItems': cartItems
        }
    print(ctx)
    return render(request, 'ecom/cart.html', ctx)

def checkout(request):
    """This view renders the checkout page
    """
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    ctx = {'items': items, 'order': order, 'cartItems':cartItems}
    return render(request, 'ecom/checkout.html', ctx)


def updateItem(request):
    """This is POST view that is used to add or delete products from user's cart
    """
    data = json.loads(request.body)
    print('data:', data)
    productId = data['productId']
    action = data['action']

    update_order_item_quantity(productId, action, request)

    return JsonResponse('Item was added', safe=False)

def processOrder(request):
    """This view is POST view and used to process the order info
    """
    data = json.loads(request.body)

    process_placed_order(request, data)

    return JsonResponse('Payment complete', safe=False)


@unauthenticated_user
def registerPage(request):
    """This view is used to render and get POST info from the user in process of registration
    """
    user_form = CreateUserForm()
    customer_form = CreateCustomerForm()

    if request.method == 'POST':
        user_form = CreateUserForm(request.POST)
        customer_form = CreateCustomerForm(request.POST)
        if user_form.is_valid() and customer_form.is_valid():
            register_new_user(request, user_form, customer_form)
            messages.success(request, 'Account was created')
            return redirect('ecom:login')

    ctx = {'user_form':user_form, 'customer_form':customer_form}
    return render(request, 'ecom/register.html', ctx)


@unauthenticated_user
def loginPage(request):
    """This view is used to render login page and check the entered data
    """

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('ecom:store')
        else:
            messages.info(request, 'Username OR password is incorrect')

    ctx = {}
    return render(request, 'ecom/login.html', ctx)

def logoutUser(request):
    """This view is used to logout the user
    """

    logout(request)

    return redirect('ecom:login')


class ProductDetail(DetailView):
    """This view renders a detail page for the chosen product
    """

    model = models.Product
    template_name = 'ecom/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data = cartData(self.request)

        cartItems = data['cartItems']

        context['cartItems'] = cartItems
        return context


def userPage(request):
    """This view renders the userpage
    """
    if not request.user.is_authenticated:
        return redirect('ecom:store')

    user = request.user

    data = cartData(request)

    cartItems = data['cartItems']

    ctx = {'user': user, 'cartItems': cartItems}
    return render(request, 'ecom/account.html', ctx)


@allowed_users(allowed_roles=['worker'])
def management(request):
    """This view renders the management page for the worker of the shop
    """
    user = request.user

    if request.method == 'POST':

        if 'add_bonuses' in request.POST:
            phone_number_add = request.POST.get('phone_number_add')
            customer = models.Customer.objects.get(phone_number=phone_number_add)

            number_of_bonuses = int(request.POST.get('number_of_bonuses_add'))

            number = add_bonuses_for_transaction(request, customer, number_of_bonuses)
            messages.info(request, ('Added '+str(number)+' bonuses'))

        elif 'remove_bonuses' in request.POST:
            phone_number_add = request.POST.get('phone_number_remove')
            customer = models.Customer.objects.get(phone_number=phone_number_add)

        return redirect('ecom:management')

    else:
        orders = models.Order.objects.filter(complete=True)
        data = cartData(request)
        cartItems = data['cartItems']
        ctx = {'user': user, 'cartItems': cartItems, 'orders': orders}
        return render(request, 'ecom/management.html', ctx)



@api_view(['GET'])
def orderDetails(request, pk):
    """This API view allows for fetching the order data from the server
    """

    order = models.Order.objects.get(id=pk)

    serializer = OrderSerializer(order, many=False)

    return Response(serializer.data)


@api_view(['GET'])
def bonusesHistory(request, pk):
    """This API view allows for fetching the bonuses fata from the server
    """
    customer = User.objects.get(id=pk).customer

    serializer = CustomerBonusesSerializer(customer, many=False)

    return Response(serializer.data)


@api_view(['GET'])
@the_same_user
def customerInfo(request, pk):
    """This API view transfers the info on the requested customer
    """

    customer = User.objects.get(id=pk).customer

    serializer = CustomerSerializer(customer, many=False)

    return Response(serializer.data)

@api_view(['PUT'])
def update_info(request):
    """This API view updates the info on the user according to the data in
    the request
    """

    data = request.body

    data = json.loads(data)

    customer = request.user.customer
    data_customer = {
        'phone_number': data['phone_number'],
        'first_name': data['first_name'],
        'last_name': data['last_name']
        }
    form_to_check = CreateCustomerForm(data_customer)
    if form_to_check.is_valid():
        phone_number = phone_formating(data['phone_number'])
        customer.phone_number = phone_number
        customer.first_name = data['first_name']
        customer.last_name = data['last_name']
        customer.save()

    user = customer.user_id
    data_user = {
        'email': data['email']
        }
    form_to_check_2 = UserEmailForm(data_user)
    if form_to_check_2.is_valid():
        user.email = data['email']
        user.save()

    return Response(status=status.HTTP_202_ACCEPTED)


@api_view(['GET'])
def get_current_user(request):
    """This API view transfers the ID of the current user
    """
    user = request.user
    serializer = UserIdSerializer(user)
    return Response(serializer.data)

@api_view(['GET'])
def get_all_orders(request):
    """This API view transfers data containing all placed orders
    """
    orders = models.Order.objects.all()
    serializer = AllOrdersSerializer(orders, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def get_customer_by_phone_number(request, phone_number):
    """This API view transfers data on the user with the corresponding phone number
    """
    try:
        phone_number = phone_formating(phone_number)
    except:
        return Response(status=status.HTTP_404_NOT_FOUND)
    customer = models.Customer.objects.get(phone_number=phone_number)

    if customer:
        serializer = CustomerSerializer(customer)
        return Response(serializer.data)
    else:
        return Response(status=status.HTTP_404_NOT_FOUND)


@allowed_users(allowed_roles=['worker'])
@api_view(['POST'])
def post_new_bonuses(request):
    data = request.body
    data = json.loads(data)

    worker_id = request.user
    customer_id = models.Customer.objects.get(id=data['customerId'])
    number_of_bonuses = data['numberOfBonuses']

    new_bonus = models.Bonuses(number_of_bonuses=number_of_bonuses, customer_id=customer_id, worker_id=worker_id)
    new_bonus.save()

    return Response(status=status.HTTP_202_ACCEPTED)


@allowed_users(allowed_roles=['worker'])
@api_view(['PUT'])
def order_accept_payment(request):
    data = request.body
    data = json.loads(data)

    order = models.Order.objects.get(id=data['id'])
    order.is_paid = True
    order.save()

    return Response(status=status.HTTP_202_ACCEPTED)


@allowed_users(allowed_roles=['worker'])
@api_view(['PUT'])
def order_serve(request):
    data = request.body
    data = json.loads(data)

    order = models.Order.objects.get(id=data['id'])
    order.served = True
    order.save()

    return Response(status=status.HTTP_202_ACCEPTED)


@allowed_users(allowed_roles=['worker'])
@api_view(['GET'])

shop/templates/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Ecom</title>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

	<script type="text/javascript">
	    var user = '{{ request.user }}'

	    function getToken(name) {
	        var cookieValue = null;
	        if (document.cookie && document.cookie !== '') {
	            var cookies = document.cookie.split(';');
	            for (var i = 0; i < cookies.length; i++) {
	                var cookie = cookies[i].trim();
	                if (cookie.substring(0, name.length + 1) === (name + '=')) {
	                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
	                    break;
	                }
	            }
	        }
	        return cookieValue;
	    }

	    var csrftoken = getToken('csrftoken');

	    function getCookie(name) {
	        var cookieArr = document.cookie.split(';');

	        for (let i = 0; i < cookieArr.length; i++) {
	            let cookiePair = cookieArr[i].split('=');

	            if (name == cookiePair[0].trim()) {
	                return decodeURIComponent(cookiePair[1]);
	            }
	        }
	        return null
	    }

	    let cart = JSON.parse(getCookie('cart'));
	    if (cart == undefined) {
	        cart = {};
	        console.log('Cart was created');
	        document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
	    }

	    console.log('cart:', cart);
	</script>

</head>
<body>


	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href="{% url 'ecom:store' %}">Ecom</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="{% url 'ecom:store' %}">Store</a>
	      </li>
	      {% with groups=user.groups.all %}
	      {% for group in groups %}
	      {% if group.name == 'worker' %}
	      <li class="nav-item active">
	        <a class="nav-link" href="{% url 'ecom:management' %}">Management</a>
	      </li>
	      {% endif %}
	      {% endfor %}
	      {% endwith %}

	    {% if user.is_authenticated %}

	    <div class="form-inline my-2 my-lg-0">
	        <ul class="navbar-nav mr-auto">
	        <li class="nav-tem active"><a class="nav-link" href="{% url 'ecom:userpage' %}">Welcome, {{ user.username }}!</a></li>
	     	<li class="nav-tem active"><a href="{% url 'ecom:logout' %}"class="btn btn-warning">Logout</a></li>
	     	</ul>

	    {% else %}

	    <div class="form-inline my-2 my-lg-0">
	     	<a href="{% url 'ecom:login' %}"class="btn btn-warning">Login</a>

	     {% endif %}

	     	<a href="{% url 'ecom:cart' %}">
	    		<img  id="cart-icon" src="{% static 'images/cart.png' %}">
	    	</a>
	    	<p id="cart-total">{{ cartItems }}</p>

	    </div>
	    </ul>
	  </div>
	</nav>

  <div class="conteiner">
    {% block content %}

    {% endblock content %}
  </div>

    <script src="https://unpkg.com/react@17/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js" crossorigin></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>

	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>


</body>
</html>