ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'ecom'), namespace='ecom'))
]

urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'ecom'
urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name='update_item'),
    path('process_order/', views.processOrder, name='process_order'),
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('<int:pk>/', views.ProductDetail.as_view(), name='details'),
    path('account/', views.userPage, name='userpage'),

    path('api/orders/all/', views.get_all_orders, name='getAllOrders'),
    path('api/orders/', views.orderDetails, name='order_details_api'),
    path('api/orders/<int:pk>', views.orderDetails, name='order_details'),
    path('api/bonuses/<int:pk>', views.bonusesHistory, name='bonusesHistory'),
    path('api/customer/<int:pk>', views.customerInfo, name='customerInfo'),
    path('api/customer/update', views.update_info, name='updateCustomer'),
    path('api/getCurrentUser/', views.get_current_user, name='getCurrentUser'),
    path('api/customerPhone/<str:phone_number>', views.get_customer_by_phone_number, name="getCustomerByPhone"),
    path('api/postNewBonuses/', views.post_new_bonuses, name="postNewBonuses"),
    path('api/order/acceptPayment/', views.order_accept_payment, name="acceptPayment"),
    path('api/order/serveOrder/', views.order_serve, name="serveOrder"),
    path('api/orders/getByPhone/<str:phone_number>', views.get_customer_orders_by_phone_number, name="getCustomerOrdersByPhone"),

    path('management/', views.management, name='management')
    ]

shop/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.db.models import Sum
from .utils import phone_validator

class Cafe(models.Model):
    adress = models.CharField(max_length=200, null=True)
    name = models.CharField(max_length=200, null=True)
    photo = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.adress


class Customer(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True, related_name='customer')
    phone_number = models.CharField('Phone Number', validators=[phone_validator], max_length=25)
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)

    def total_bonuses(self):
        boni = self.bonuses_set.all()
        sum = boni.aggregate(Sum('number_of_bonuses'))
        return sum['number_of_bonuses__sum']

    def __str__(self):
        return self.phone_number


class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    image = models.ImageField(null=True, blank=True)
    description = models.TextField(default='Here be descriptions')

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except ValueError:
            url = '/images/placeholder.png'
        return url


class Order(models.Model):
    PAYMENT_METHODS = (
        (1, 'Cash'),
        (2, 'Online')
        )
    customer_id = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    served = models.BooleanField(default=False, null=True, blank=False)
    is_paid = models.BooleanField(default=False, null=True, blank=False)
    payment_method = models.CharField(max_length=1, choices=PAYMENT_METHODS, null=True)
    transaction_id = models.CharField(max_length=200, null=True)
    cafe_id = models.ForeignKey(Cafe, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order_id = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    @property
    def get_total(self):
        total = self.product_id.price * self.quantity
        return total

    def __str__(self):
        return self.product_id.name

class Bonuses(models.Model):
    number_of_bonuses = models.IntegerField(default=0, null=True, blank=True)
    customer_id = models.ForeignKey(Customer, on_delete=models.CASCADE)
    worker_id = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

shop/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Customer
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CreateCustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['first_name', 'last_name', 'phone_number']


class UserEmailForm(ModelForm):
    class Meta:
        model = User
        fields = ['email']

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import models
from django.http import JsonResponse
from .utils import cartData, guestOrder, add_bonuses_for_transaction, phone_formating, update_order_item_quantity, process_placed_order, register_new_user
from .serializers import OrderSerializer, CustomerBonusesSerializer, CustomerSerializer, UserIdSerializer, AllOrdersSerializer, CustomerOrdersSerializer
import json
import datetime
from . forms import CreateUserForm, CreateCustomerForm, UserEmailForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from rest_framework.response import Response
from rest_framework.decorators import api_view
from django.contrib.auth.models import User
from .decorators import unauthenticated_user, allowed_users, the_same_user
from rest_framework import status
import phonenumbers

def store(request):
    """This view renders the main page of the e-shop showing all the products in the database
    """
    data = cartData(request)

    cartItems = data['cartItems']

    products = models.Product.objects.all()
    ctx = {
        'products':products,
        'cartItems': cartItems
        }
    return render(request, 'ecom/store.html', ctx)

def cart(request):
    """This view renders the cart of the user
    """
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    ctx = {
        'items': items,
        'order': order,
        'cartItems': cartItems
        }
    print(ctx)
    return render(request, 'ecom/cart.html', ctx)

def checkout(request):
    """This view renders the checkout page
    """
    data = cartData(request)

    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    ctx = {'items': items, 'order': order, 'cartItems':cartItems}
    return render(request, 'ecom/checkout.html', ctx)


def updateItem(request):
    """This is POST view that is used to add or delete products from user's cart
    """
    data = json.loads(request.body)
    print('data:', data)
    productId = data['productId']
    action = data['action']

    update_order_item_quantity(productId, action, request)

    return JsonResponse('Item was added', safe=False)

def processOrder(request):
    """This view is POST view and used to process the order info
    """
    data = json.loads(request.body)

    process_placed_order(request, data)

    return JsonResponse('Payment complete', safe=False)


@unauthenticated_user
def registerPage(request):
    """This view is used to render and get POST info from the user in process of registration
    """
    user_form = CreateUserForm()
    customer_form = CreateCustomerForm()

    if request.method == 'POST':
        user_form = CreateUserForm(request.POST)
        customer_form = CreateCustomerForm(request.POST)
        if user_form.is_valid() and customer_form.is_valid():
            register_new_user(request, user_form, customer_form)
            messages.success(request, 'Account was created')
            return redirect('ecom:login')

    ctx = {'user_form':user_form, 'customer_form':customer_form}
    return render(request, 'ecom/register.html', ctx)


@unauthenticated_user
def loginPage(request):
    """This view is used to render login page and check the entered data
    """

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('ecom:store')
        else:
            messages.info(request, 'Username OR password is incorrect')

    ctx = {}
    return render(request, 'ecom/login.html', ctx)

def logoutUser(request):
    """This view is used to logout the user
    """

    logout(request)

    return redirect('ecom:login')


class ProductDetail(DetailView):
    """This view renders a detail page for the chosen product
    """

    model = models.Product
    template_name = 'ecom/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data = cartData(self.request)

        cartItems = data['cartItems']

        context['cartItems'] = cartItems
        return context


def userPage(request):
    """This view renders the userpage
    """
    if not request.user.is_authenticated:
        return redirect('ecom:store')

    user = request.user

    data = cartData(request)

    cartItems = data['cartItems']

    ctx = {'user': user, 'cartItems': cartItems}
    return render(request, 'ecom/account.html', ctx)


@allowed_users(allowed_roles=['worker'])
def management(request):
    """This view renders the management page for the worker of the shop
    """
    user = request.user

    if request.method == 'POST':

        if 'add_bonuses' in request.POST:
            phone_number_add = request.POST.get('phone_number_add')
            customer = models.Customer.objects.get(phone_number=phone_number_add)

            number_of_bonuses = int(request.POST.get('number_of_bonuses_add'))

            number = add_bonuses_for_transaction(request, customer, number_of_bonuses)
            messages.info(request, ('Added '+str(number)+' bonuses'))

        elif 'remove_bonuses' in request.POST:
            phone_number_add = request.POST.get('phone_number_remove')
            customer = models.Customer.objects.get(phone_number=phone_number_add)

        return redirect('ecom:management')

    else:
        orders = models.Order.objects.filter(complete=True)
        data = cartData(request)
        cartItems = data['cartItems']
        ctx = {'user': user, 'cartItems': cartItems, 'orders': orders}
        return render(request, 'ecom/management.html', ctx)



@api_view(['GET'])
def orderDetails(request, pk):
    """This API view allows for fetching the order data from the server
    """

    order = models.Order.objects.get(id=pk)

    serializer = OrderSerializer(order, many=False)

    return Response(serializer.data)


@api_view(['GET'])
def bonusesHistory(request, pk):
    """This API view allows for fetching the bonuses fata from the server
    """
    customer = User.objects.get(id=pk).customer

    serializer = CustomerBonusesSerializer(customer, many=False)

    return Response(serializer.data)


@api_view(['GET'])
@the_same_user
def customerInfo(request, pk):
    """This API view transfers the info on the requested customer
    """

    customer = User.objects.get(id=pk).customer

    serializer = CustomerSerializer(customer, many=False)

    return Response(serializer.data)

@api_view(['PUT'])
def update_info(request):
    """This API view updates the info on the user according to the data in
    the request
    """

    data = request.body

    data = json.loads(data)

    customer = request.user.customer
    data_customer = {
        'phone_number': data['phone_number'],
        'first_name': data['first_name'],
        'last_name': data['last_name']
        }
    form_to_check = CreateCustomerForm(data_customer)
    if form_to_check.is_valid():
        phone_number = phone_formating(data['phone_number'])
        customer.phone_number = phone_number
        customer.first_name = data['first_name']
        customer.last_name = data['last_name']
        customer.save()

    user = customer.user_id
    data_user = {
        'email': data['email']
        }
    form_to_check_2 = UserEmailForm(data_user)
    if form_to_check_2.is_valid():
        user.email = data['email']
        user.save()

    return Response(status=status.HTTP_202_ACCEPTED)


@api_view(['GET'])
def get_current_user(request):
    """This API view transfers the ID of the current user
    """
    user = request.user
    serializer = UserIdSerializer(user)
    return Response(serializer.data)

@api_view(['GET'])
def get_all_orders(request):
    """This API view transfers data containing all placed orders
    """
    orders = models.Order.objects.all()
    serializer = AllOrdersSerializer(orders, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def get_customer_by_phone_number(request, phone_number):
    """This API view transfers data on the user with the corresponding phone number
    """
    try:
        phone_number = phone_formating(phone_number)
    except:
        return Response(status=status.HTTP_404_NOT_FOUND)
    customer = models.Customer.objects.get(phone_number=phone_number)

    if customer:
        serializer = CustomerSerializer(customer)
        return Response(serializer.data)
    else:
        return Response(status=status.HTTP_404_NOT_FOUND)


@allowed_users(allowed_roles=['worker'])
@api_view(['POST'])
def post_new_bonuses(request):
    data = request.body
    data = json.loads(data)

    worker_id = request.user
    customer_id = models.Customer.objects.get(id=data['customerId'])
    number_of_bonuses = data['numberOfBonuses']

    new_bonus = models.Bonuses(number_of_bonuses=number_of_bonuses, customer_id=customer_id, worker_id=worker_id)
    new_bonus.save()

    return Response(status=status.HTTP_202_ACCEPTED)


@allowed_users(allowed_roles=['worker'])
@api_view(['PUT'])
def order_accept_payment(request):
    data = request.body
    data = json.loads(data)

    order = models.Order.objects.get(id=data['id'])
    order.is_paid = True
    order.save()

    return Response(status=status.HTTP_202_ACCEPTED)


@allowed_users(allowed_roles=['worker'])
@api_view(['PUT'])
def order_serve(request):
    data = request.body
    data = json.loads(data)

    order = models.Order.objects.get(id=data['id'])
    order.served = True
    order.save()

    return Response(status=status.HTTP_202_ACCEPTED)


@allowed_users(allowed_roles=['worker'])
@api_view(['GET'])

shop/templates/ecom/account.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
{{ user.id|json_script:"user-data" }}

{% csrf_token %}

<div class='row'>

<div class="col-md-4">
<div><h1>Hello, {{ user.username }}!</h1></div>

<div class="card" style="width: 75%">
<div id="personal-info-list">
</div>
<div id='management-buttons'>
    {% if user.customer.total_bonuses > 0 %}
    <li class="list-group-item"><button id="bonuses-button" class="btn btn-primary">Your number of bonuses: {{ user.customer.total_bonuses }} </button></li>
    {% else %}
    <p>You don't have any bonuses yet! Order something so we can add you some bonuses!</p>
    {% endif %}
    <button id="change-info-button" class="btn btn-primary">Change your personal information</button>
</div>
</div>
</div>

<div class="col-md-4">
<h1>Your orders:</h1>
<div class="card" style="overflow-y: scroll; height: 50vh; width: 75%">
    {% for order in user.customer.order_set.all %}
    {% if order.transaction_id != None %}
    <button id={{ order.id }} class="btn btn-primary order-button" style="margin: 0; margin-top: 5px">Order # {{ order.id }}{% if order.served %} <p>Closed</p> {% else %} <p>Active</p> {% endif %}</button>
    {% endif %}
    {% endfor %}
</div>
</div>
<div id="additional-info" class="col-md-4">

</div>

</div>

	<script type="text/babel" src="{% static 'js/reactBonuses.js' %}"></script>

	<script type="text/babel" src="{% static 'js/updatePersonalInfo.js' %}"></script>

	<script type="text/babel" src="{% static 'js/reactOrders.js' %}"></script>

    <script type="text/babel">
	        initOrderButtons(false)
	        initBonusesButton()
    </script>
{% endblock content %}

shop/templates/ecom/cart.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

    	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="{% url 'ecom:store' %}">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{ order.get_cart_items }}</strong></h5></th>
						<th><h5>Total:<strong> ${{ order.get_cart_total|floatformat:2 }}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'ecom:checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
                {% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{ item.product_id.imageURL }}"></div>
					<div style="flex:2"><p>{{ item.product_id.name }}</p></div>
					<div style="flex:1"><p>${{ item.product_id.price|floatformat:2 }}</p></div>
					<div style="flex:1">
						<p class="quantity">x{{ item.quantity }}</p>
						<div class="quantity">
							<img data-product="{{ item.product_id.id }}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

							<img data-product="{{ item.product_id.id }}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>${{ item.get_total|floatformat:2 }}</p></div>
				</div>
				{% endfor %}

			</div>
		</div>
	</div>

{% endblock content %}

shop/templates/ecom/checkout.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
   <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">

						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>

						<div class="form-field">
							<input required class="form-control" type="tel" name="phone_number" placeholder="Phone number.."
							pattern="/^[+]\d{11}$|^8\d{10}$|^[(]d{3}[)]d{7}$|^[(]d{3}[)]d{3}[-]d{2}[-]d{2}$/"
							title="Enter the valid phone number">
						</div>
					</div>

						<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal Options</small>
				<button id="make-payment">Make Payment</button>
			</div>

		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'ecom:cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{ item.product_id.imageURL }}"></div>
					<div style="flex:2"><p>{{ item.product_id.name }}</p></div>
					<div style="flex:1"><p>${{ item.product_id.price|floatformat:2 }}</p></div>
					<div style="flex:1"><p>x{{ item.quantity }}</p></div>
				</div>
				{% endfor %}
				<h5>Items:   {{ order.get_cart_items }}</h5>
				<h5>Total:   ${{ order.get_cart_total|floatformat:2 }}</h5>
			</div>
		</div>
	</div>
	<script type="text/javascript">
	    var total = '{{ order.get_cart_total }}'

	    if (user != 'AnonymousUser') {
	        document.getElementById('user-info').innerHTML = ''
	    }

	    var form = document.getElementById('form');

	    form.addEventListener('submit', function(e) {
	        e.preventDefault();
	        console.log('Form submitted...')
	        document.getElementById('form-button').classList.add('hidden')
	        document.getElementById('payment-info').classList.remove('hidden')
	    })

	    var button_payment = document.getElementById('make-payment');

	    button_payment.addEventListener('click', function(e) {
	        submitFormData()
	    })

	    function submitFormData() {
	        console.log('Payment button clicked')

	        var userFormData = {
	            'name':null,
	            'phone_number':null,
	            'total':total,
	        }

	        if (user == 'AnonymousUser') {
	            userFormData.name = form.name.value;
	            userFormData.phone_number = form.phone_number.value;
	        }

	        var url = '/process_order/'

	        fetch(url, {
	            method: 'POST',
	            headers: {
	                'Content-Type':'application/json',
	                'X-CSRFToken':csrftoken,
	            },
	            body:JSON.stringify({'form':userFormData})
	        }).then((response) => response.json()).then((data) => {
	            console.log('Success:', data);
	            alert('Transaction completed');

	            cart = {};
	            document.cookie = "cart=" + JSON.stringify(cart) + ";domain;path=/";

	            window.location.href = "https://youtu.be/dQw4w9WgXcQ"
	        })

	    }


	</script>
{% endblock content %}

shop/templates/ecom/detail.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">{{ product.name }}</h3>
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-6">
                    <div class="white-box text-center"><img src="{{ product.imageURL }}" class="thumbnail"></div>
                </div>
                <div class="col-lg-7 col-md-7 col-sm-6">
                    <h4 class="box-title mt-5">Product description</h4>
                    <p>{{ product.description }}</p>
                    <h2 class="mt-5">
                        ${{ product.price }}
                    </h2>
                    <button data-product="{{ product.id }}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
{% endblock content %}

shop/templates/ecom/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
				   			<div class="d-flex justify-content-center">
					            <h3 id="form-title"><a href="{% url 'ecom:store' %}">BACK</a></h3>
					        </div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'ecom:register' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>

shop/templates/ecom/management.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<div class="row">
<div id="all-orders-list" class="col-md-4" style="overflow-y: scroll; height: 100vh">

</div>

<div class="col-md-4" style="overflow-y: scroll; height: 100vh">
    <div>
        <h1>The order</h1>
    </div>

    <div id="bonuses-search">

    </div>
    <div class="phone-order-list">

    </div>
    <div id="additional-info">

    </div>
    <div id="order-management-buttons">

    </div>
</div>

<div class="col-md-4">

    <div id="bonuses-manipulation">

    </div>
</div>

    <script src="https://unpkg.com/redux@latest/dist/redux.min.js"></script>

    <script src="https://unpkg.com/react-redux@5.0.7/dist/react-redux.min.js"></script>

	<script type="text/babel" src="{% static 'js/reactOrders.js' %}"></script>

	<script type="text/babel" src="{% static 'js/allOrders.js' %}"></script>

	<script type="text/babel" src="{% static 'js/bonusesManipulation.js' %}"></script>

	<script type="text/babel">
	    initSearchInterface()
	</script>


{% endblock content %}

shop/templates/ecom/store.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
	<div class="row">
		{% for product in products %}
		<div class="col-lg-4">
		    <div class="box-element product">
		        <div class="text-center">
		            <img class="thumbnail" src="{{ product.imageURL }}">
		        </div>
		        <h6><strong>{{ product.name }}</strong></h6>
		        <hr>

		        <button data-product="{{ product.id }}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
		        <a class="btn btn-outline-success" href="{% url 'ecom:details' product.id %}">View</a>
		        <h4 style="display: inline: block; float: right"><strong>${{ product.price|floatformat:2 }}</strong></h4>
		    </div>
		</div>
		{% endfor %}
	</div>
{% endblock content %}